[profile.release]
panic = 'abort'
opt-level = 'z'
lto = 'thin'

[workspace]
resolver = "2"

members = [
  "rockc",
  "rock",
  "lib",
]

[workspace.dependencies]
clap = { version = "4.5.3", features = ["derive"] }
ariadne = { version = "0.4.1", features = ["auto-color"] }
paste = "1.0.15"

# default-members = ["rock"]
