mod test_parse_function_decl;
mod test_parse_function_decl_monoline;
mod test_parse_function_decl_multiline;
mod test_parse_function_shorthand;
mod test_parse_function_shorthand_2;
mod test_parse_operator_function;
mod test_lambda_shortcut_space_requirement;
