[theme]
name = "slick"
[theme.overrides]
idle_bg = "#1e2122"
idle_fg = "#abcdef"
info_bg = "#FFC622"
info_fg = "#000000"
warning_bg = "#FF6666"
warning_fg = "#000000"
critical_bg = "#FF0000"
critical_fg = "#000000"

[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width = 100
show_marks = "all"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} + {aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = ""
critical_updates_regex = "(linux |linux-lts|linux-zen)"
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "pikaur -Qua"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
signal_strength = true
speed_up = false
graph_down = true
interval = 5
use_bits = false
hide_inactive = true

[[block]]
block = "net"
device = "enp62s0u1u4"
speed_up = false
graph_down = true
interval = 5
use_bits = false
hide_inactive = true

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
# format = "{alias} {bar} {available} {unit}"

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
warning_mem = 60.0
critical_mem = 80.0

[[block]]
block = "load"
interval = 1

[[block]]
block = "cpu"
interval = 1
info = 10
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "temperature"
# collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
chip = "*-isa-*"
good = 45
idle = 60
info = 70
warning = 90

[[block]]
block = "sound"

[[block]]
block = "backlight"

# [[block]]
# block = "speedtest"
# bytes = true
# interval = 1800


[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
