[theme]
theme = "slick"
[theme.overrides]
idle_bg = "#1e2122"
idle_fg = "#abcdef"
good_bg = "#1e2122"
good_fg = "#abcdef"
info_bg = "#888888"
info_fg = "#000000"
warning_bg = "#FF7700"
warning_fg = "#000000"
critical_bg = "#FF1111"
critical_fg = "#000000"

[icons]
icons = "awesome4"

[[block]]
block = "focused_window"
# max_width = 100
# show_marks = "all"

[[block]]
block = "pacman"
interval = 600
format = " $icon $pacman updates available "
format_singular = " $icon $pacman update available "
format_up_to_date = " $icon up to date "
critical_updates_regex = "(linux |linux-lts|linux-zen)"
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "pikaur -Qua"

[[block]]
block = "net"
device = "^wlan0$"
# format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device $bitrate"


# [[block]]
# block = "networkmanager"

#[[block]]
#block = "net"
#device = "wlp2s0"
#ssid = true
#signal_strength = true
#speed_up = false
#graph_down = true
#interval = 5
#use_bits = false
#hide_inactive = true

# [[block]]
# block = "net"
# device = "enp62s0u1u4"
# speed_up = false
# graph_down = true
# interval = 5
# use_bits = false
# hide_inactive = true

[[block]]
block = "disk_space"
path = "/"
# alias = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 10.0
alert = 5.0
# format = "{alias} {bar} {available} {unit}"

[[block]]
block = "disk_space"
path = "/home"
# alias = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 10.0
alert = 5.0

[[block]]
block = "memory"
# display_type = "memory"
# format_mem = "{Mup}%"
# format_swap = "{SUp}%"
warning_mem = 60.0
critical_mem = 80.0

[[block]]
block = "load"
interval = 1
warning = 2.00
critical = 7.00

[[block]]
block = "cpu"
interval = 1
# info = 10
# warning = 20
format = " $icon $barchart $utilization $frequency "

[[block]]
block = "temperature"
# collapsed = false
interval = 10
# format = " $min min, $max max, $average avg "
chip = "coretemp-isa-0000"
idle = 40
good = 60
info = 80
warning = 90

[[block]]
block = "sound"

[[block]]
block = "backlight"

# [[block]]
# block = "speedtest"
# bytes = true
# interval = 1800


[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %d/%m %R', l:fr_FR) "

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage $time "
