#[options]
#font = Iosevka Nerd Font 32

#[character]      # The name of the module we are configuring is "character"
#symbol = "➜"     # The "symbol" segment is being set to "➜"

[rust]
symbol = "⚙️ "

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold orange"

[[battery.display]]
threshold = 75
style = "bold green"

[character]
error_symbol = "✗"
use_symbol_for_status = true

[directory]
style = "bold yellow"
truncate_to_repo = false
truncation_length = 8

#[env_var]
#variable = "SHELL"
#default = "unknown shell"
#style = "dimmed white"

[git_commit]
commit_hash_length = 8
only_detached = false

[memory_usage]
show_percentage = true
show_swap = true
threshold = 75
style = "bold dimmed green"
disabled = false

[time]
disabled = false
style = "dimmed white"
